
export const colorValueMap: Record<string, string> = {
  'Multicam Black': '#131211/#58534a',
  'White/Black': '#ffffff/#0c0c0c',
  'White/Pink': '#ffffff/#ff93d9',
  'Black': '#0b0b0b',
  'Solid Black Blend': '#000000',
  'Solid White Blend': '#ffffff',
  'White': '#FFFFFF',
  'Dark Heather': '#46484d',
  'Heather Grey': '#a19f9b',
  'Heather': '#bebebe',
  'Grey': '#554e46',
  'Charcoal Heather': '#423d3a',
  'Charcoal Gray': '#4d4f4c',
  'Charcoal': '#6e6661',
  'Dark Grey': '#2d2a2a',
  'Dark Grey Heather': '#2b2b2b',
  'Grey Heather': '#e7e7e7',
  'Gunmetal Heather': '#9e9e9e',
  'Sport Grey': '#ccccce',
  'Ice Grey': '#e9dddc',
  'Light Blue': '#cbdbec',
  'Light Pink': '#f3d4e3',
  'Baby Pink': '#ffc6cd',
  'Pink': '#ffd6d3',
  'Ash': '#f3f3f3',
  'Silver': '#c0c0c0',
};